# Site settings
title: 'Elexis'

  #description:
  #de: "Elexis ist eine umfassende open source Software für die Arztpraxis, welche 2008 von Dr. Gerry Weirich entwickelt wurde und seither von der Medelexis AG, den Entwicklern und Anwendern laufend verbessert wurde."
  #fr: "Elexis est un logicial libre pour un cabinet médical, developpé par le médecin généralist Dr. Gerry Weirich. La version française est utilisé dans un seul cabinet médical et attend de nouveaux clients prêt à tester."
  #en: "Elexis is an Eclipse RCP program for all aspects of a medical practice: electronic medical record (EMR), laboratory findings etc., as well as accounting, billing (swiss TARMED-System, other systems to be developped) and other daily work."
  #it: "Elexis è un software open source completo per lo studio medico, sviluppato in gran parte dal Dr. Gerry Weirich. La versione italiana è in attesa di valutatori (tester alpha)."

baseurl: '/' # the subpath of your site, e.g. /blog
absoluteurl: 'https://ranbureand.github.io/multilingual-experiment'
url: '' # the base hostname & protocol for your site, e.g. http://example.com

version: '2021-01-01'

default_language: 'de'

timezone: Europe/Rome
encoding: utf-8

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3

# Defaults
defaults:
-
  scope:
    path: '_posts/de'
    type: 'posts'
  values:
    permalink: 'de/story/:title'
    language: de 
-
  scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/story/:title'
    language: en
-
  scope:
    path: '_posts/fr'
    type: 'posts'
  values:
    permalink: 'fr/story/:title'
    language: fr 
-
  scope:
    path: '_posts/it'
    type: 'posts'
  values:
    permalink: 'it/storia/:title'
    language: it
